Repository benedict-soh/G5-SSE-2020-Project, pull requests merged in 2020-10, with the labels that each got.

#6 improving readme
  flask-api/README.md
Labels: documentation

#18 Adding register, login, logout features
  flask-api/API_endpoint.md
  flask-api/README.md
  flask-api/flaskr/__init__.py
  flask-api/flaskr/auth.py
  flask-api/requirements.txt
  flask-api/setup.sh
Labels: documentation, enhancement

#19 Voting Event API
  flask-api/API_endpoint.md
  flask-api/flaskr/__init__.py
  flask-api/flaskr/auth.py
  flask-api/flaskr/voting_event.py
Labels: documentation, enhancement

#20 Candidate & Party API
  flask-api/API_endpoint.md
  flask-api/flaskr/__init__.py
  flask-api/flaskr/candidate.py
  flask-api/flaskr/party.py
  flask-api/flaskr/voting_event.py
Labels: documentation, enhancement

#22 Updating doc to what is needed
  flask-api/API_endpoint.md
Labels: documentation

#27 added and tested
  flask-api/flaskr/__init__.py
  flask-api/flaskr/auth.py
Labels: enhancement

#26 Voting event CRUD pages
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/voting_events.js
  frontend/src/navigation/NavigationTopBar.js
  frontend/src/voting_events/votingEventEdit.js
  frontend/src/voting_events/votingEventForm.js
  frontend/src/voting_events/votingEventList.js
Labels: enhancement

#31 Voting endpoint
  flask-api/API_endpoint.md
  flask-api/flaskr/__init__.py
  flask-api/flaskr/candidate.py
  flask-api/flaskr/vote.py
  flask-api/flaskr/voting_event.py
Labels: documentation, enhancement

#33 adding /auth/get-role, updating API doc
  flask-api/API_endpoint.md
  flask-api/flaskr/auth.py
Labels: enhancement

#36 Updated API Endpoints
  flask-api/API_endpoint.md
  flask-api/flaskr/auth.py
  flask-api/flaskr/candidate.py
  flask-api/flaskr/party.py
  flask-api/flaskr/vote.py
  flask-api/flaskr/voting_event.py
Labels: documentation

#41 yep
  flask-api/API_endpoint.md
  flask-api/flaskr/vote.py
  flask-api/flaskr/voting_event.py
Labels: enhancement

#46 Login bug fix + logout feature
  frontend/src/App.js
  frontend/src/login/login.js
  frontend/src/login/logout.js
  frontend/src/navigation/NavigationTopBar.js
  frontend/src/utils/API.js
Labels: bug
